### PR TITLE
add webpage siddharthparmar

### PR DESCRIPTION
**Pull request by Siddharth11**

### CODE REVIEW

**Comment by MridulS** [comment]
@Siddharth11 Add yourself to 201X.html also

**Comment by Siddharth11** [comment]
@MridulS done

**Comment by MridulS** [comment]
@Siddharth11 Thanks !! :)

**Comment by Siddharth11** [comment]
@MridulS let me know if you need any help with the project. I'd be happy to help.

**Comment by MridulS** [comment]
@Siddharth11  I guess if you can make the index.html prettier that will be great. Right
now I am using a simple bootstrap panel. Thanks :)

**Comment by MridulS** [comment]
Also have a look at issues. Feel free to open an issue if you have any particular idea :)

**Pull request merged**
